# Generated by Django 5.2.7 on 2025-10-18 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=10, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Année Scolaire',
                'verbose_name_plural': 'Années Scolaires',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.IntegerField(default=0)),
                ('date_activation', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Crédit',
                'verbose_name_plural': 'Crédits',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/photos/')),
                ('statut', models.CharField(choices=[('nouvel_inscrit', 'Nouvel inscrit'), ('reinscrit', 'Réinscrit')], default='nouvel_inscrit', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.FloatField(default=1.0)),
                ('niveau', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=20)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='TypeDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de Départ',
                'verbose_name_plural': 'Types de Départ',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/photos/')),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='enseignants/identites/')),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=20)),
                ('effectif', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.anneescolaire')),
                ('enseignant_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.enseignant')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='AssignationClasseMatiereEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.matiere')),
            ],
            options={
                'verbose_name': 'Assignation Classe-Matière-Enseignant',
                'verbose_name_plural': 'Assignations Classe-Matière-Enseignant',
                'unique_together': {('classe', 'matiere', 'enseignant')},
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Créé'), ('update', 'Modifié'), ('delete', 'Supprimé'), ('login', 'Connecté'), ('logout', 'Déconnecté'), ('autre', 'Autre')], max_length=20)),
                ('entite', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('classe', 'Classe'), ('note', 'Note'), ('paiement', 'Paiement'), ('bulletin', 'Bulletin'), ('utilisateur', 'Utilisateur'), ('autre', 'Autre')], max_length=50)),
                ('entite_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.matiere')),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'verbose_name_plural': 'Emplois du Temps',
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(through='gestion.AssignationClasseMatiereEnseignant', to='gestion.matiere'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('interrogation', 'Interrogation'), ('devoir', 'Devoir'), ('examen', 'Examen')], max_length=20)),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('sur', models.FloatField(default=20)),
                ('date', models.DateField()),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2e Trimestre'), (3, '3e Trimestre')])),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.matiere')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('type', models.CharField(choices=[('inscription', 'Inscription'), ('scolarite', 'Scolarité'), ('frais', 'Frais'), ('autre', 'Autre')], max_length=20)),
                ('recu_numero', models.CharField(max_length=50, unique=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='RelationEtudiantParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur'), ('autre', 'Autre')], max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.parent')),
            ],
            options={
                'verbose_name': 'Relation Étudiant-Parent',
                'verbose_name_plural': 'Relations Étudiant-Parent',
                'unique_together': {('etudiant', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parents',
            field=models.ManyToManyField(through='gestion.RelationEtudiantParent', to='gestion.parent'),
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('raison_detail', models.TextField(blank=True, null=True)),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='departures/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.enseignant')),
                ('etudiant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
                ('type_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.typedepart')),
            ],
            options={
                'verbose_name': 'Départ',
                'verbose_name_plural': 'Départs',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2e Trimestre'), (3, '3e Trimestre')])),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bulletins/')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'unique_together': {('etudiant', 'classe', 'trimestre', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='AssignationEtudiantClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.etudiant')),
            ],
            options={
                'verbose_name': 'Assignation Étudiant-Classe',
                'verbose_name_plural': 'Assignations Étudiant-Classe',
                'unique_together': {('etudiant', 'classe', 'annee_scolaire')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_scolaire')},
        ),
    ]
